const ERROR_CODE_INVALID = 400;
const ERROR_CODE_NOT_FOUND = 404;
const ERROR_CODE_SERVER = 500;
const CODE_OK = 200;

module.exports = {
  ERROR_CODE_INVALID,
  ERROR_CODE_NOT_FOUND,
  ERROR_CODE_SERVER,
  CODE_OK,
};
